[tool.poetry]
name = "aou discord"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
discord = "^1.7.3"
discord-py-slash-command = "^2.3.2"
python-dotenv = "^0.19.0"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"
pre-commit = "^2.13.0"
taskipy = "^1.8.1"

[tool.taskipy.tasks]
bot = { cmd = "python -m bot", help = "Run the bot" }
lint = { cmd = "pre-commit run --all-files", help = "Lints project" }
precommit = { cmd = "pre-commit install", help = "Installs the pre-commit hook" }
format = { cmd = "black .", help = "Runs the black python formatter" }


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
